version: 1.0.{build}
image: Visual Studio 2019

# Build configuration
build_script:
  - cmd: dotnet build test.sln --configuration Release

# Define the artifacts to be uploaded after a successful build
artifacts:
  - path: bin\Release\net461\*.exe
    name: MyExecutable
