version: 1.0.{build}
image: Visual Studio 2019

# Build configuration
build_script:
  - cmd: dotnet build Crop/Crop.csproj --configuration Debug

# Define the artifacts to be uploaded after a successful build
artifacts:
  - path: Crop\bin\Debug\*.exe
    name: Executables
